name: publish nuget
on:
  push:
    branches:
      - master # Default release branch

defaults:
  run:
    working-directory: src

jobs:
  publish:
    name: Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release
      - run: dotnet test --no-build -c Release -l trx -r .
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-results
          path: src/*.trx
      - run: dotnet pack --no-build -c Release -o .
      - uses: actions/upload-artifact@v4
        with:
          name: packages
          path: src/*nupkg
      - run: dotnet nuget push *.nupkg -s nuget.org -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
